import {
  User,
  Lead,
  Message,
  Sale,
  DashboardStats,
  FunnelData,
  RevenueChartData,
} from "./types";

// Mock Users (matching current layout auth)
export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Tunde Bakare",
    email: "tunde@smartsales.ai",
    role: "admin",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Tunde%20Bakare",
  },
  {
    id: "u2",
    name: "Amina Bello",
    email: "amina@smartsales.ai",
    role: "sales",
    avatar: "https://api.dicebear.com/7.x/initials/svg?seed=Amina%20Bello",
  },
];

// Mock Leads (12+ items, with varied status and channels, localized)
export const MOCK_LEADS: Lead[] = [
  {
    id: "l1",
    name: "Chinelo Obi",
    phone: "+234 803 111 2222",
    channel: "whatsapp",
    status: "hot",
    lastMessage: "I need to order 50 units of the Premium Ankara bundle.",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(), // 5 mins ago
    unreadCount: 2,
    intentTags: ["Buying", "Pricing"],
  },
  {
    id: "l2",
    name: "Babajide Alao",
    phone: "+234 812 333 4444",
    channel: "web",
    status: "new",
    lastMessage: "Do you offer delivery to Abuja?",
    lastMessageTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 mins ago
    unreadCount: 1,
    intentTags: ["Inquiry"],
  },
  {
    id: "l3",
    name: "Ngozi Adebayo",
    phone: "+234 705 555 6666",
    channel: "instagram",
    status: "warm",
    lastMessage: "What are your wholesale rates for the skincare kit?",
    lastMessageTime: new Date(Date.now() - 2 * 3600 * 1000).toISOString(), // 2 hrs ago
    unreadCount: 0,
    intentTags: ["Pricing"],
  },
  {
    id: "l4",
    name: "Emeka Nwosu",
    phone: "+234 901 777 8888",
    channel: "whatsapp",
    status: "closed",
    lastMessage: "Payment successful! Send receipt.",
    lastMessageTime: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Buying"],
  },
  {
    id: "l5",
    name: "Fatima Yusuf",
    phone: "+234 809 999 0000",
    channel: "web",
    status: "lost",
    lastMessage: "That is out of my budget, thank you.",
    lastMessageTime: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Pricing"],
  },
  {
    id: "l6",
    name: "Olumide Johnson",
    phone: "+234 802 444 5555",
    channel: "whatsapp",
    status: "hot",
    lastMessage: "Can we integrate this with our POS system?",
    lastMessageTime: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Support", "Inquiry"],
  },
  {
    id: "l7",
    name: "Yetunde Sowemimo",
    phone: "+234 816 777 1111",
    channel: "instagram",
    status: "warm",
    lastMessage: "Sent you a DM about the wedding souvenirs.",
    lastMessageTime: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Inquiry"],
  },
  {
    id: "l8",
    name: "Chidi Okafor",
    phone: "+234 703 888 2222",
    channel: "web",
    status: "new",
    lastMessage: "My checkout page is showing an error code.",
    lastMessageTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    unreadCount: 3,
    intentTags: ["Support", "Complaint"],
  },
  {
    id: "l9",
    name: "Aisha Mohammed",
    phone: "+234 818 999 3333",
    channel: "whatsapp",
    status: "closed",
    lastMessage: "Thank you for the prompt delivery!",
    lastMessageTime: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Support"],
  },
  {
    id: "l10",
    name: "Bioye Faloyin",
    phone: "+234 805 111 4444",
    channel: "instagram",
    status: "hot",
    lastMessage: "I want to purchase the standard pack right now.",
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Buying"],
  },
  {
    id: "l11",
    name: "Kelechi Nnamdi",
    phone: "+234 902 222 5555",
    channel: "web",
    status: "new",
    lastMessage: "Are you open on Sundays for pickups?",
    lastMessageTime: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    unreadCount: 1,
    intentTags: ["Inquiry"],
  },
  {
    id: "l12",
    name: "Bisi Akande",
    phone: "+234 708 333 6666",
    channel: "whatsapp",
    status: "warm",
    lastMessage: "Do you have the blue variant in stock?",
    lastMessageTime: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    unreadCount: 0,
    intentTags: ["Inquiry"],
  },
];

// Mock Messages for conversations (indexed by leadId)
export const MOCK_MESSAGES: Record<string, Message[]> = {
  l1: [
    {
      id: "m1",
      leadId: "l1",
      sender: "customer",
      content: "Hello! I am looking at the custom Ankara bundles advertised on Instagram.",
      timestamp: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      id: "m2",
      leadId: "l1",
      sender: "ai",
      content: "Welcome! 👋 Yes, our Premium Ankara bundles are currently in stock! We have the 6-yard bundles starting at ₦35,000. Would you like to see our latest pattern catalog?",
      timestamp: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
      intentTag: "Inquiry",
    },
    {
      id: "m3",
      leadId: "l1",
      sender: "customer",
      content: "Yes please, send the catalog. Also what is the delivery fee to Lekki Phase 1?",
      timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: "m4",
      leadId: "l1",
      sender: "ai",
      content: "Here is our latest catalog: [Ankara_Catalog_Q2.pdf]! Delivery to Lekki Phase 1 is ₦2,500 via our express courier, and it arrives in 24 hours. 🚚",
      timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
      intentTag: "Pricing",
    },
    {
      id: "m5",
      leadId: "l1",
      sender: "customer",
      content: "Great. I need to order 50 units of the Premium Ankara bundle.",
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
  ],
  l2: [
    {
      id: "m6",
      leadId: "l2",
      sender: "customer",
      content: "Hi there. I'm browsing your store. Do you offer delivery to Abuja?",
      timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: "m7",
      leadId: "l2",
      sender: "ai",
      content: "Hello! Yes, we ship nationwide! 🇳🇬 Delivery to Abuja takes 2-3 business days and costs ₦4,000 for standard shipping. Would you like us to set up an order for you?",
      timestamp: new Date(Date.now() - 14 * 60 * 1000).toISOString(),
      intentTag: "Inquiry",
    },
  ],
  l8: [
    {
      id: "m8",
      leadId: "l8",
      sender: "customer",
      content: "Hi. I'm trying to buy the wholesale skincare package, but my checkout page is showing an error code. Something like SEC_ERROR_404.",
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
  ],
  l10: [
    {
      id: "m9",
      leadId: "l10",
      sender: "customer",
      content: "Is the discount coupon 'WELCOME10' still active? I want to purchase the standard pack right now.",
      timestamp: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
  ],
};

// Mock Sales (15+ items, using Naira amounts)
export const MOCK_SALES: Sale[] = [
  {
    id: "s1",
    customer: "Emeka Nwosu",
    product: "Premium Ankara Bundle (x5)",
    amount: 175000,
    status: "completed",
    date: new Date(Date.now() - 4 * 3600 * 1000).toISOString(), // 4 hrs ago
    channel: "whatsapp",
  },
  {
    id: "s2",
    customer: "Aisha Mohammed",
    product: "Skincare Glow Kit (x2)",
    amount: 54000,
    status: "completed",
    date: new Date(Date.now() - 24 * 3600 * 1000).toISOString(), // 1 day ago
    channel: "whatsapp",
  },
  {
    id: "s3",
    customer: "Tolu Omidiran",
    product: "Wholesale Souvenir Box",
    amount: 250000,
    status: "completed",
    date: new Date(Date.now() - 36 * 3600 * 1000).toISOString(),
    channel: "instagram",
  },
  {
    id: "s4",
    customer: "Chike Uzor",
    product: "Ankara Fabrics (Standard)",
    amount: 45000,
    status: "pending",
    date: new Date(Date.now() - 1 * 3600 * 1000).toISOString(), // 1 hr ago
    channel: "web",
  },
  {
    id: "s5",
    customer: "Funmi Adeleke",
    product: "Organic Shea Butter Pack",
    amount: 28000,
    status: "refunded",
    date: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
    channel: "instagram",
  },
  {
    id: "s6",
    customer: "Halima Danjuma",
    product: "Premium Ankara Bundle",
    amount: 35000,
    status: "completed",
    date: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
    channel: "whatsapp",
  },
  {
    id: "s7",
    customer: "Uche Okeke",
    product: "Luxury Body Butter",
    amount: 19500,
    status: "completed",
    date: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    channel: "web",
  },
  {
    id: "s8",
    customer: "Kemi Balogun",
    product: "Aso Oke Bridal Set",
    amount: 480000,
    status: "completed",
    date: new Date(Date.now() - 5 * 24 * 3600 * 1000).toISOString(),
    channel: "instagram",
  },
  {
    id: "s9",
    customer: "Ibrahim Lawal",
    product: "Skincare Glow Kit",
    amount: 27000,
    status: "pending",
    date: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    channel: "web",
  },
  {
    id: "s10",
    customer: "Nneka Egwu",
    product: "Ankara Headwrap (x3)",
    amount: 15000,
    status: "completed",
    date: new Date(Date.now() - 6 * 24 * 3600 * 1000).toISOString(),
    channel: "whatsapp",
  },
  {
    id: "s11",
    customer: "Femi Falana",
    product: "Beaded Handbag Accessory",
    amount: 85000,
    status: "completed",
    date: new Date(Date.now() - 7 * 24 * 3600 * 1000).toISOString(),
    channel: "instagram",
  },
  {
    id: "s12",
    customer: "Bunmi Thomas",
    product: "Scented Candles Box (x10)",
    amount: 60000,
    status: "completed",
    date: new Date(Date.now() - 8 * 24 * 3600 * 1000).toISOString(),
    channel: "web",
  },
  {
    id: "s13",
    customer: "Daniel Ojo",
    product: "Premium Ankara Bundle (x2)",
    amount: 70000,
    status: "completed",
    date: new Date(Date.now() - 9 * 24 * 3600 * 1000).toISOString(),
    channel: "whatsapp",
  },
  {
    id: "s14",
    customer: "Joy Benson",
    product: "Skincare Tester Kit",
    amount: 8500,
    status: "completed",
    date: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    channel: "instagram",
  },
  {
    id: "s15",
    customer: "Tope Alabi",
    product: "Wholesale Souvenir Box (x2)",
    amount: 500000,
    status: "pending",
    date: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    channel: "whatsapp",
  },
];

// Mock Stats
export const MOCK_STATS: DashboardStats = {
  totalChatsToday: 247,
  newLeads: 38,
  salesClosed: 12,
  revenueGenerated: 184500,
  chatsChange: 12,
  leadsChange: -5,
  salesChange: 18,
  revenueChange: 24,
};

// Mock Funnel Data
export const MOCK_FUNNEL_DATA: FunnelData[] = [
  { stage: "New Leads", count: 248, color: "#2563EB" },
  { stage: "Interested", count: 142, color: "#7C3AED" },
  { stage: "Negotiating", count: 67, color: "#F97316" },
  { stage: "Converted", count: 34, color: "#22C55E" },
];

// Mock Revenue Chart Data
export const MOCK_REVENUE_CHART: RevenueChartData[] = [
  { day: "Mon", revenue: 45000, leads: 18 },
  { day: "Tue", revenue: 78000, leads: 22 },
  { day: "Wed", revenue: 52000, leads: 15 },
  { day: "Thu", revenue: 110000, leads: 31 },
  { day: "Fri", revenue: 95000, leads: 29 },
  { day: "Sat", revenue: 140000, leads: 38 },
  { day: "Sun", revenue: 184500, leads: 42 },
];
